# Generated by Django 3.2.5 on 2021-08-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('description', models.CharField(max_length=10000)),
                ('image', models.CharField(max_length=10000)),
                ('url', models.CharField(max_length=10000)),
                ('useUrl', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('description', models.CharField(max_length=10000)),
                ('image', models.CharField(max_length=10000)),
                ('url', models.CharField(max_length=10000)),
                ('useUrl', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('description', models.CharField(max_length=10000)),
                ('image', models.CharField(max_length=10000)),
                ('url', models.CharField(max_length=10000)),
                ('useUrl', models.BooleanField()),
            ],
        ),
    ]
