# Generated by Django 3.2.5 on 2021-08-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10000)),
                ('name', models.CharField(max_length=10000)),
                ('description', models.CharField(max_length=10000)),
                ('image', models.CharField(max_length=10000)),
                ('url', models.CharField(max_length=10000)),
                ('useUrl', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
