# Generated by Django 3.2.5 on 2021-08-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_entry_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subentry',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
