# Generated by Django 3.2.5 on 2021-08-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_subentry_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subentry',
            name='url',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
