# Generated by Django 3.2.5 on 2021-08-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_subentry_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='ip',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
